_name_or_path:
    value: Qwen/Qwen2.5-1.5B-Instruct
_wandb:
    value:
        cli_version: 0.26.1
        e:
            6t9de2oj11tkl8u4alpx2ni716kw8jwl:
                args:
                    - --model_name
                    - Qwen/Qwen2.5-1.5B-Instruct
                    - --data_name
                    - argilla/ultrafeedback-binarized-preferences-cleaned
                    - --save_dir
                    - ./qwen2.5-1.5b-llm-success
                    - --enable_lora
                    - --num_proc
                    - "1"
                    - --lr
                    - "5e-6"
                    - --per_device_train_batch_size
                    - "1"
                    - --gradient_accumulation_steps
                    - "8"
                    - --max_train_samples
                    - "100"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "502392610816"
                        used: "445145915392"
                email: mmubashirmemon@gmail.com
                executable: /home/mubashirmemon/anaconda3/envs/nlp-env/bin/python
                git:
                    commit: e3bda2a8854ef5c8eadde5910998f16dfe2f3d07
                    remote: https://github.com/mubashir72/NLP.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-3e441960-0855-5624-a0c4-85cbee0e38e8
                host: GPU-RAWAL
                memory:
                    total: "33353211904"
                os: Linux-6.8.0-110-generic-x86_64-with-glibc2.39
                program: /home/mubashirmemon/Downloads/NLP LLM Alignment/NLP/main.py
                python: CPython 3.10.20
                root: /home/mubashirmemon/Downloads/NLP LLM Alignment/NLP
                startedAt: "2026-04-30T04:48:58.013511Z"
                writerId: 6t9de2oj11tkl8u4alpx2ni716kw8jwl
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 7
                - 13
                - 19
                - 62
                - 66
            "4": 3.10.20
            "5": 0.26.1
            "6": 5.6.2
            "9":
                "1": transformers_trainer
            "12": 0.26.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - Qwen2ForCausalLM
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 151643
chunk_size_feed_forward:
    value: 0
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_static_graph:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: true
dtype:
    value: bfloat16
enable_jit_checkpoint:
    value: false
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value:
        use_reentrant: false
greater_is_better:
    value: null
hidden_act:
    value: silu
hidden_size:
    value: 1536
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
intermediate_size:
    value: 8960
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 5e-06
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./checkpoints/ultrafeedback-binarized-preferences-cleaned/Qwen2.5-1.5B-Instruct-ultrafeedback-binarized-preferences-cleaned-lambda1.0-ORPO-30-4-48/logs
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 50
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_position_embeddings:
    value: 32768
max_steps:
    value: -1
max_window_layers:
    value: 21
metric_for_best_model:
    value: null
model/num_parameters:
    value: 1552430592
model_type:
    value: qwen2
neftune_noise_alpha:
    value: null
num_attention_heads:
    value: 12
num_hidden_layers:
    value: 28
num_key_value_heads:
    value: 2
num_train_epochs:
    value: 10
optim:
    value: paged_adamw_32bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./checkpoints/ultrafeedback-binarized-preferences-cleaned/Qwen2.5-1.5B-Instruct-ultrafeedback-binarized-preferences-cleaned-lambda1.0-ORPO-30-4-48
output_hidden_states:
    value: false
pad_token_id:
    value: null
parallelism_config:
    value: null
peft_config:
    value:
        default:
            alora_invocation_tokens: null
            arrow_config: null
            auto_mapping: null
            base_model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
            bias: none
            corda_config: null
            ensure_weight_tying: false
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 16
            lora_bias: false
            lora_dropout: 0.1
            lora_ga_config: null
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            peft_version: 0.19.1
            qalora_group_size: 16
            r: 64
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - q_proj
                - v_proj
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_bdlora: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 2
per_device_train_batch_size:
    value: 1
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
quantization_config:
    value:
        _load_in_4bit: true
        _load_in_8bit: false
        bnb_4bit_compute_dtype: float16
        bnb_4bit_quant_storage: uint8
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: true
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: BITS_AND_BYTES
remove_unused_columns:
    value: false
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
rms_norm_eps:
    value: 1e-06
rope_parameters:
    value:
        rope_theta: 1e+06
        rope_type: default
run_name:
    value: Qwen2.5-1.5B-Instruct-ultrafeedback-binarized-preferences-cleaned-lambda1.0-ORPO-30-4-48
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
skip_memory_metrics:
    value: true
sliding_window:
    value: null
tf32:
    value: null
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_bucket_id:
    value: null
trackio_space_id:
    value: null
trackio_static_space_id:
    value: null
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.6.2
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
use_sliding_window:
    value: false
vocab_size:
    value: 151936
warmup_ratio:
    value: null
warmup_steps:
    value: 5000
weight_decay:
    value: 0
