_wandb:
    value:
        cli_version: 0.26.0
        e:
            4wyo8w2nmgxkh99aan02vi455pbb9o2q:
                args:
                    - --model_name
                    - microsoft/phi-2
                    - --data_name
                    - argilla/ultrafeedback-binarized-preferences-cleaned
                    - --save_dir
                    - ./phi-2-orpo-results
                    - --enable_lora
                    - --num_proc
                    - "0"
                    - --lr
                    - "5e-6"
                    - --per_device_train_batch_size
                    - "1"
                    - --gradient_accumulation_steps
                    - "16"
                    - --prompt_max_length
                    - "128"
                    - --response_max_length
                    - "256"
                codePath: main.py
                codePathLocal: main.py
                email: abdullahahmed693@gmail.com
                executable: E:\Fast\Sem2\NLP\Project\Code\orpo\venv\Scripts\python.exe
                git:
                    commit: 208d2d648068e700cbb1ae0e8320b1dc99b014ec
                    remote: https://github.com/xfactlab/orpo
                host: DESKTOP-UT0L1N5
                os: Windows-11-10.0.26200-SP0
                program: E:\Fast\Sem2\NLP\Project\Code\orpo\main.py
                python: CPython 3.13.4
                root: E:\Fast\Sem2\NLP\Project\Code\orpo
                startedAt: "2026-04-19T19:10:50.512431Z"
                writerId: 4wyo8w2nmgxkh99aan02vi455pbb9o2q
        m: []
        python_version: 3.13.4
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 13
            "4": 3.13.4
            "5": 0.26.0
            "6": 5.5.4
            "8":
                - 3
            "12": 0.26.0
            "13": windows-amd64
