_wandb:
    value:
        cli_version: 0.26.0
        e:
            j4qddpdp3u2khvctevjhgf7lg5wj098k:
                args:
                    - --model_name
                    - microsoft/phi-2
                    - --data_name
                    - argilla/ultrafeedback-binarized-preferences-cleaned
                    - --save_dir
                    - ./phi-2-orpo-success
                    - --enable_lora
                    - --lr
                    - "5e-6"
                    - --per_device_train_batch_size
                    - "1"
                    - --gradient_accumulation_steps
                    - "8"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "838860795904"
                        used: "489527390208"
                email: abdullahahmed693@gmail.com
                executable: E:\Fast\Sem2\NLP\Project\Code\orpo\venv\Scripts\python.exe
                git:
                    commit: 208d2d648068e700cbb1ae0e8320b1dc99b014ec
                    remote: https://github.com/xfactlab/orpo
                gpu: NVIDIA GeForce GTX 1050
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 640
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce GTX 1050
                      uuid: GPU-c2660bc4-7f55-7a88-a7e8-7813a2188bda
                host: DESKTOP-UT0L1N5
                memory:
                    total: "34196336640"
                os: Windows-11-10.0.26200-SP0
                program: E:\Fast\Sem2\NLP\Project\Code\orpo\main.py
                python: CPython 3.13.4
                root: E:\Fast\Sem2\NLP\Project\Code\orpo
                startedAt: "2026-04-19T18:33:42.416563Z"
                writerId: j4qddpdp3u2khvctevjhgf7lg5wj098k
        m: []
        python_version: 3.13.4
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 13
            "4": 3.13.4
            "5": 0.26.0
            "6": 5.5.4
            "8":
                - 3
            "12": 0.26.0
            "13": windows-amd64
